[package]
name = "cobra-bindless-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
categories = ["no-std::no-alloc"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[lints]
workspace = true