[package]
name = "cobra-bindless"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
spirv-std = { workspace = true }
cobra-bindless-macro = { path = "../cobra-bindless-macro" }

[lints]
workspace = true
